### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by OddMorning** [MikeKovarik/rage-edit#9]
After experimenting with `iconv-lite`, `cmd.exe /u`, and other things, I found a workaround that allows to read unicode characters from registry. The idea is to execute [**chcp 65001**](https://ss64.com/nt/chcp.html) before reading something from registry and then return code page using **chcp 437 / 866 / whatever** (otherwise terminal's code page will stay 65001 even after node.js finishes its job). Some say 65001 is dangerous and doesn't always work but in my case it works with cyrillic, chinese, arabic characters, and even emoji.

It's easy to write an external wrapper for `Registry.get` for personal use. But I wonder if is it too unreliable way for something like `Registry.unicode = true`, a new short method like `Registry.uget`, or `{ unicode: true }`? It's sad it can't be enabled by default because every `spawn` slows down the code a bit (≈7ms VS ≈26ms for example below) but it still would be nice to have something simple and handy for reading.

I know you're quite busy so all of that are just ideas at the moment.

And here's the example that doesn't touch `rage-edit`'s source code:
```js
const { promisify } = require('util')
const cp = require('child_process')
const execAsync = promisify(cp.exec) // `spawn` is ≈1.5 times faster but `exec` is shorter

class Codepage {
  static async get() {
    const { stdout } = await execAsync('cmd.exe /c chcp')
    const regexpResult = /\d+/.exec(stdout) // `Active code page: 437` => `437`
    const codepage = regexpResult ? parseInt(regexpResult[0]) : null

    if (codepage) {
      return codepage
    } else {
      throw new Error(`Can't get current code page`)
    }
  }

  static async set(encoding) {
    try {
      await execAsync(`cmd.exe /c chcp ${encoding}`)
    } catch (e) {
      throw new Error(`Invalid code page: ${encoding}`)
    }
  }
}



;(async () => {
  try {
    const { Registry } = require('rage-edit')
    const cp = await Codepage.get()
    const key = 'HKLM\\Software\\Test'
    const name = 'Unicode'
    let value

    await Registry.set(key, name, 'Registry - Реестр - 注册处 - سجل')

    value = await Registry.get(key, name)
    console.log(' Default encoding:', value) // Registry - ������ - ??? - ???

    await Codepage.set(65001)
    value = await Registry.get(key, name)
    await Codepage.set(cp)
    console.log(' UTF8 encoding:   ', value) // Registry - Реестр - 注册处 - سجل

  } catch (error) {
    console.log(error)
  }
})()
```
![04 12 2018 20-00-50 vivaldi](https://user-images.githubusercontent.com/12204657/49479672-e348ff80-f834-11e8-80bc-0ba5edbb1635.png)

**Comment by MikeKovarik** [comment]
Hi. tbh i didn't conscider unicode and didn't even know you could switch cmd to unicode mode.

It looks like a cool and "easy" to implement feature. For now I'd just stick with static methods `Registry.enableUnicode()` to get it going. In the future we could add `{unicode}` option since we're adding `{mode}` but that only requires adding one more argument whereas unicode would require copy-pasting 5 more lines into each method, making the code unnecessarily more complex.

Regarding spawn. Afaik exec opens cmd or shell on linux in which it then executes the expression. So I'd go with spawn because it will only create one process instead of two. I've played around with it in REPL yesterday and it works. Plus there's already promisified function in rage-edit which we could generalize and use https://github.com/MikeKovarik/rage-edit/blob/master/src/util.mjs#L46

Also, instead of Regex I'd go with
```js
Number(stdout.split(':')[1])
```

I miiiiight squeeze some time out of tonight to get this done. As always. tests would be awesome

**Comment by MikeKovarik** [comment]
Hi. So I implemented my vision of the first wave. I did not test this though. I just played around it with it (and the Number() method) in REPL yesterday and I have high hopes that the changes i did to util.mjs work (those i did test). I suppose you can take it from here.
